### ISSUE TITLE
Please ensure that basemap is installed correctly during Travis tests, and add tests for plots.py

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#60] opened 2017-03-27 21:36 UTC
The module `desiutil.plots` needs [basemap](https://github.com/matplotlib/basemap) for some functions.  However, the [basemap documentation](http://matplotlib.org/basemap/users/installing.html) suggests that the install procedure is somewhat more complicated than just `pip install git+https://github.com/matplotlib/basemap.git`.

Please ensure that:

* basemap is being installed correctly during Travis tests.
* That there are at least some tests to verify that basemap is installed correctly.
* Finally, please provide instructions on how to install basemap on NERSC systems, and ensure that it is being installed correctly in the DESI+Anaconda system.

**Comment by dkirkby** [comment] 2017-03-27 23:01
We already spent quite a lot of time trying to get this to work in desihub/desiutil/pull#52 but I am re-assigning to @fjaviersanchez in case he has any new ideas.

I'm not sure there is any requirement to install basemap on NERSC since this is an optional utility function primarily for use in jupyter notebooks (but @fjaviersanchez says it should be easy to install at NERSC).

**Comment by weaverba137** [comment] 2017-03-27 23:24
Perhaps I should have phrased the title as "Please add tests for plots.py, and as a corollary, ensure that basemap is installed correctly."  I'm not sure that the current tests in `desiutil.test.test_plots` cover the functions that use basemap.

**Comment by fjaviersanchez** [comment] 2017-03-27 23:43
Right now `python setup.py test` checks whether `basemap` is installed or not:

``
try:
    import mpl_toolkits.basemap
    have_basemap = True
except ImportError:
    have_basemap = False
``

and if it is installed it performs one test: 

``
@unittest.skipIf(not have_basemap, 'Skipping tests of plot_sky that require basemap to be installed first')
    def test_plot_sky(self):
        """Test plot_sky
        """
        from ..plots import plot_sky_binned
        ra = 360.*np.random.rand(200)
        dec = 360.*np.random.rand(200)
        #Run
        ax = plot_sky_binned(ra, dec)
        if 'TRAVIS_JOB_ID' not in os.environ:
            plt.savefig(self.plot_file2)
``

I checked it at cori using `2.7-anaconda` and it passes the test that requires basemap:

``
test_plot_sky (desiutil.test.test_plots.TestPlots)
Test plot_sky ... ok
``

When I try to install `basemap` using anaconda in Edison and Cori it says that the package is already installed:

``pip install basemap --user
Requirement already satisfied (use --upgrade to upgrade): basemap in /global/common/edison/software/python/2.7-anaconda/lib/python2.7/site-packages``

I think I skipped basemap in Travis because I had a lot of trouble making it run there (which I didn't manage to do). Do you want me to try again and see if I can make it run?

**Comment by sbailey** [comment] 2017-03-28 00:24
If it is tested away from Travis, and you've already spent unsuccessful time trying to get it to work on Travis (I now remember some emails about that), I'm ok with not doing any more right now.  Ben may have a different opinion and/or other ideas.

This ticket from Ben was triggered by my asking about desiutil Travis tests being much slower than they used to be because it is compiling basemap from source.  If desiutil switches to ci-helpers or some sort of conda-based system, it may become easier and faster to install basemap.

We do eventually want basemap to be part of our desi-conda environment at NERSC.  There are backburner plans for figuring out + documenting how to connect our python environments to jupyter-dev.nersc.gov which would enable jupyter notebook analysis of DESI data without having to download it.

**Comment by weaverba137** [comment] 2017-03-28 16:12
My main concerned is that we have a low-level, core library that depends on an unversioned github respository, rather than a versioned package that can be trivially installed with conda or pip.

Further, given that the install instructions are non-trivial, we need some quality assurance on the installation procedure, whatever it is.

**Comment by fjaviersanchez** [comment] 2017-03-28 16:36
The latest version is not available yet at `pypi` but you can install `basemap` using `pip install basemap`. Should I change the `requirements.txt` file to use this dependency instead (or take it out from requirements.txt to speed up the Travis' tests since we are not using it in Travis anyway?)

**Comment by weaverba137** [comment] 2017-03-28 16:46
I'm fine with putting the PyPI version in requirements.txt or removing it entirely.  However, that does not address the question of QA on the install when it *does* need to be installed.

**Comment by sbailey** [comment] 2017-03-29 17:02
`pip install basemap` doesn't seem to work:
```
[master*] desiutil $ pip install basemap
Collecting basemap
  Could not find a version that satisfies the requirement basemap (from versions: )
No matching distribution found for basemap
```
We could pin to a specific tag via `pip install git+https://github.com/matplotlib/basemap.git@v1.0.7rel` though even that isn't sufficient since you have to have the GEOS library pre-installed in a location that basemap can find.

I had no problems installing it with `conda install basemap` and I confirmed that if it is installed, the tests do have coverage for the functions that use it.

I suggest that we treat this as an "optional dependency" and remove it from requirements.txt .  That keeps the desiutil dependencies lighter, and if someone does want to use those plot functions in desiutil they can still install basemap after desiutil was installed.

**Comment by weaverba137** [comment] 2017-03-29 17:14
I think that is the way forward, although I would like to see instructions *in* the desiutil documentation about installing optional dependencies, including this one.

**Closed** 2017-04-05 22:54 UTC
Labels: question
