### ISSUE TITLE
Minimum python is 2.7.10?

### ISSUE THREAD

**Issue by apcooper** [desihub/desiutil#38] opened 2016-06-28 10:19 UTC
When I installed ```desiutil``` locally [I mistakenly guessed it needed python 3](https://github.com/desihub/desitarget/issues/50#issuecomment-226828352) because I got this from```setup.py install```:

```
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from desiutil.setup import DesiModule, DesiTest, DesiVersion, get_version
  File "/cosma/home/dph3apc/modules/desi_stack/python2/git/desiutil/py/desiutil/setup.py", line 29, in <module>
    from .modules import configure_module, process_module, default_module
  File "/cosma/home/dph3apc/modules/desi_stack/python2/git/desiutil/py/desiutil/modules.py", line 129
    exec(out, globals(), locals())
SyntaxError: unqualified exec is not allowed in function 'desiutil_module' it is a nested function
```
I've since discovered this works fine in 2.7.10, but not in 2.7.3 (which I was using) or 2.7.8. I haven't tested anything in between. I can find lots of info on this being fixed in 3.x but nothing obvious regarding what changed by 2.7.10.

Is the minimum python requirement documented anywhere?

**Comment by weaverba137** [comment] 2016-06-28 13:52
Actually it's 2.7.9.  This is a duplicate of #25, #26.

This is mentioned here: https://desi.lbl.gov/trac/wiki/Computing/Software/Guidelines#PythonVersion.

In some sense, this is moot because the full migration to Python 3 is imminent.  Also, we have mostly been using Anaconda Python distributions, which keep the 2.7 version very up-to-date.

**Closed** 2016-06-28 17:51 UTC
Labels: duplicate
